# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-09 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.CharField(max_length=30)),
                ('popularity', models.FloatField(default=0.0)),
                ('original_title', models.CharField(max_length=100)),
                ('backdrop_path', models.CharField(max_length=300)),
                ('poster_path', models.CharField(max_length=300)),
                ('vote_count', models.IntegerField(default=0)),
                ('video', models.BooleanField(default=True)),
                ('adult', models.BooleanField(default=True)),
                ('vote_average', models.FloatField(default=0.0)),
                ('original_language', models.CharField(max_length=30)),
            ],
        ),
    ]
