# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-09 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_movie_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='backdrop_path',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
