# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-09 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_auto_20170309_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster_path',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
